### ISSUE TITLE
论文代码

### ISSUE THREAD

**Issue by lipx2022** [caoyunkang/CPMF#2] opened 2023-11-01 01:37 UTC
您的论文，拜读了，很新颖就有极大的创新突破。我想试下论文中的模型，能开源下您的代码吗？让我们学习学习

**Comment by caoyunkang** [comment] 2023-11-04 09:45
Thanks for your interest. The code will be released once the paper is accepted :)

**Comment by caoyunkang** [comment] 2023-11-08 19:19
Hi! I have uploaded the code. Please contact me if any questions.

**Comment by woshi-xiaobai** [comment] 2023-12-01 02:14
Hello！Some errors occur when the program is running，“'(MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /timm/wide_resnet50_2.racm_in1k/resolve/main/model.safetensors (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001C987862408>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: 335fe39b-2f7c-4f84-8a06-5635f1000e2d)')' thrown while requesting HEAD https://huggingface.co/timm/wide_resnet50_2.racm_in1k/resolve/main/model.safetensors
'(MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /timm/wide_resnet50_2.racm_in1k/resolve/main/pytorch_model.bin (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001C987873208>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: 8945c24b-8ea5-4a72-ac4a-2f43dec167dc)')' thrown while requesting HEAD https://huggingface.co/timm/wide_resnet50_2.racm_in1k/resolve/main/pytorch_model.bin”

**Comment by caoyunkang** [comment] 2023-12-02 08:58
Hi, it seems to be the network issue, and you cannot connect huggingface correctly. You could download some files to specific directories in advance to solve this issue.

**Comment by jklln** [comment] 2023-12-25 07:56
Hello, the following error occurred while the program was running，
File "/home/jklln/AD_CODE/CPMF/feature_extractors/cpmf_features.py", line 24, in calculate_single_view_feature
    pcd_features.append(f_resize[:, :, position[0, 1, :], position[0, 0, :]])
IndexError: index 777 is out of bounds for dimension 0 with size 224

**Comment by caoyunkang** [comment] 2023-12-26 09:05
@woshi-xiaobai Hi. I have updated reuqirements ``pip install timm==0.6.11``. This could avoid to connect huggingface in China, which can address you problem.

**Comment by caoyunkang** [comment] 2023-12-26 09:05
@jklln Hi, I didn't suffer problems like yours. Can you provide more details?

**Comment by yuanj1ng** [comment] 2024-01-11 04:20
When I run main.py  and category=rope ,The following error will be reported in the program，
/home/jing/anaconda3/envs/jing/bin/python /home/jing/PycharmProjects/CPMF-master/main.py 
=========================================
data_path: /home/jing/PycharmProjects/CPMF-master/datasets/mvtec_3d_multiview
n_views: 1
no_fpfh: False
use_rgb: True
exp_name: default
category: rope
root_dir: ./results
backbone: resnet18
draw: False
=========================================

 default 


Running on class rope

resnet18
2024-01-11 11:52:21.902 | INFO     | data.mvtec3d_cpmf:__init__:41 - img path: /home/jing/PycharmProjects/CPMF-master/datasets/mvtec_3d_multiview/rope/train
Extracting train features for class rope:  37%|███▋      | 110/298 [00:21<00:37,  5.00it/s]
Traceback (most recent call last):
  File "/home/jing/PycharmProjects/CPMF-master/main.py", line 43, in <module>
    run_3d_ads(args)
  File "/home/jing/PycharmProjects/CPMF-master/main.py", line 20, in run_3d_ads
    patchcore.fit()
  File "/home/jing/PycharmProjects/CPMF-master/patchcore_runner_cpmf.py", line 29, in fit
    self.method.add_sample_to_mem_bank(sample)
  File "/home/jing/PycharmProjects/CPMF-master/feature_extractors/cpmf_features.py", line 48, in add_sample_to_mem_bank
    view_invariant_features = self.calculate_view_invariance_feature(sample)
  File "/home/jing/PycharmProjects/CPMF-master/feature_extractors/cpmf_features.py", line 37, in calculate_view_invariance_feature
    pcd_feature_list.append(self.calculate_single_view_feature(view_image, position))
  File "/home/jing/PycharmProjects/CPMF-master/feature_extractors/cpmf_features.py", line 23, in calculate_single_view_feature
    pcd_features.append(f_resize[:, :, position[0, 1, :], position[0, 0, :]])
IndexError: index 599 is out of bounds for dimension 0 with size 224

**Comment by caoyunkang** [comment] 2024-01-11 11:42
@yuanj1ng This result is weird. You could check the rendered results and make sure it looks the same as our paper. In addition, you could try other categories to confirm whether the results are consistent with our reported results. Hope these suggestions make sense!

**Comment by LeungDDT** [comment] 2024-02-01 11:12
> # When I run main.py and category=rope ,The following error will be reported in the program，
> /home/jing/anaconda3/envs/jing/bin/python /home/jing/PycharmProjects/CPMF-master/main.py
> # data_path: /home/jing/PycharmProjects/CPMF-master/datasets/mvtec_3d_multiview
> n_views: 1
> no_fpfh: False
> use_rgb: True
> exp_name: default
> category: rope
> root_dir: ./results
> backbone: resnet18
> draw: False
> default
> 
> Running on class rope
> 
> resnet18 2024-01-11 11:52:21.902 | INFO | data.mvtec3d_cpmf:**init**:41 - img path: /home/jing/PycharmProjects/CPMF-master/datasets/mvtec_3d_multiview/rope/train Extracting train features for class rope: 37%|███▋ | 110/298 [00:21<00:37, 5.00it/s] Traceback (most recent call last): File "/home/jing/PycharmProjects/CPMF-master/main.py", line 43, in run_3d_ads(args) File "/home/jing/PycharmProjects/CPMF-master/main.py", line 20, in run_3d_ads patchcore.fit() File "/home/jing/PycharmProjects/CPMF-master/patchcore_runner_cpmf.py", line 29, in fit self.method.add_sample_to_mem_bank(sample) File "/home/jing/PycharmProjects/CPMF-master/feature_extractors/cpmf_features.py", line 48, in add_sample_to_mem_bank view_invariant_features = self.calculate_view_invariance_feature(sample) File "/home/jing/PycharmProjects/CPMF-master/feature_extractors/cpmf_features.py", line 37, in calculate_view_invariance_feature pcd_feature_list.append(self.calculate_single_view_feature(view_image, position)) File "/home/jing/PycharmProjects/CPMF-master/feature_extractors/cpmf_features.py", line 23, in calculate_single_view_feature pcd_features.append(f_resize[:, :, position[0, 1, :], position[0, 0, :]]) IndexError: index 599 is out of bounds for dimension 0 with size 224

Hello, I got the same error when running on the bagel category. Do you have any idea now?

**Comment by YubingChan** [comment] 2024-03-28 12:51
I also encountered the same IndexError when I was training the rope file.
IndexError: index 631 is out of bounds for dimension 0 with size 224.
Does somebody know how to fix this?

**Comment by caoyunkang** [comment] 2024-03-28 16:09
@YubingChan Hi, do you manage to get reasonable results for other categories? or have you run the preprocess.py to remove the background?

**Comment by YubingChan** [comment] 2024-03-29 06:52
> @YubingChan Hi, do you manage to get reasonable results for other categories? or have you run the preprocess.py to remove the background?

Hello, thank you for your attention. I have already successfully run the proprocess.py, and only the rope category reported this problem.

**Comment by YubingChan** [comment] 2024-04-03 02:06
> I also encountered the same IndexError when I was training the rope file. IndexError: index 631 is out of bounds for dimension 0 with size 224. Does somebody know how to fix this?

It seems I have found the problem. The preprocess file can only be run once. When I run it a second time, there is an error in extracting the images.

**Comment by caoyunkang** [comment] 2024-04-03 08:05
@YubingChan Thanks a lot! The preprocess.py will remove the background and should be run only once.

**Closed as completed by caoyunkang** 2024-04-03 08:05 UTC
